# Generated by Django 2.2.22 on 2021-05-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photo_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='record',
            new_name='record_img',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='title',
        ),
        migrations.AddField(
            model_name='photo',
            name='record_vid',
            field=models.FileField(default='exit', upload_to='images/'),
            preserve_default=False,
        ),
    ]
