# Generated by Django 2.2.22 on 2021-05-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='media_img_video',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
